; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
platform_packages =
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.3.7
board = freenove_esp32_s3_wroom
framework = arduino
lib_deps = 
	gilmaimon/ArduinoWebsockets@^0.5.4
	sparkfun/SparkFun VL53L5CX Arduino Library@^1.0.3
	sd_read_write = symlink://../libs/sd_read_write
	camera_pins = symlink://../libs/camera_pins
	freenove/Freenove WS2812 Lib for ESP32@^2.0.1
board_build.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 8MB

monitor_speed = 115200
monitor_filters = time
monitor_port = //dev/ttyACM0
upload_port = /dev/ttyACM0